### ISSUE TITLE
[web] Update landing page

### ISSUE THREAD

**Issue by hanburger97** [myriadeinc/web#11]
Currently our landing page has only the bare minimum.

__Acceptance criteria:__

* Provide more user friendly information and better user experience for people to sign up.
* Provide a temporary email list sign up for users to be updated when new features roll out

Refer to the document posted in #design channel.

## Goal

To provide a better user experience and converge more users

**Comment by sqphoenix** [comment]
[What we are.docx](https://github.com/myriadeinc/web/files/3965984/What.we.are.docx)

This is the file

(closed by accident)
