### ISSUE TITLE
[web] Tweaks for the landing page

### ISSUE THREAD

**Issue by JonathanXu1** [myriadeinc/web#12]
@sqphoenix would like a few tweaks to what we currently have on the landing page:

- [x]  Change the color code for the alert on the main landing page to HEX f07c00
- [x] Route the get started button to what the signup button is currently routed to
- [x] Change the signup button to login
- [x] Fix page width overflow on the home page
- [x] Add red stars next to everything that is required in the signup form (everything minus monero wallet address)
- [x] Move the monero wallet address field below the email auth token field in the form
- [x] Make cursor show the finger state instead of the edit text state when hovering over the "Start mining" page's tab view
- [x] Increase logo size on navbar
- [x] Put the favicon back in the browser tab
- [x] Change landing page header to:
> The first Fortune-Mining Pool.
> Made for Monero.
- [x] Change "Name" field to "Username" in step 2
- [x] Change prompt: "Confirm your email address" to "Enter your email address" in step 1
- [ ] Remove '#' from main url

@sqphoenix please let me know if I missed anything

**Comment by sqphoenix** [comment]
Forgot to add, right now there is a # after the website's address. I.e when on the homepage it is https://myriade.io/#/ and on the login page it's https://myriade.io/#/login. Could we remove the # ?

**Comment by JonathanXu1** [comment]
Sounds good. I'll add that to the list

**Comment by hanburger97** [comment]
The '#' is due to our use of Hashrouter, we can potentially use regular router instead, the only concern is that we need to be careful so that it doesnt conflict with our backend route, but it should be fine for now since our backend are under a different subdomain e.g. `staging.myriade.io`

**Comment by sqphoenix** [comment]
Oh, well if it makes it easier then i don't mind the # too much when there is a slug after the domain. Like in https://myriade.io/#/login it doesn't make much difference if it's there or not. If it could be removed from the homepage though then that would have the same effect i was thinking of. So just turn https://myriade.io/#/ into https://myriade.io  if that's possible.
