### ISSUE TITLE
Change to signup form part 2

### ISSUE THREAD

**Issue by sqphoenix** [myriadeinc/web#16]
In the signup form, there is the "username" field. For the moment, the place where you put in a username is ghost filled with the words "John Doe". My fear is that this will confuse people into writing in their first and last names. it might be for the best if we just remove the ghost fields alltogether

**Comment by JonathanXu1** [comment]
Do you think it would be better if we added an "e.g." in front to clarify that it's an example?

**Username**
```
e.g. John Doe
```
