### ISSUE TITLE
[web] Fix the favicon issue

### ISSUE THREAD

**Issue by sqphoenix** [myriadeinc/web#49]
The favicon does not load on google chrome, and on firefox it is stretched. Please make sure they also work on safari and edge and that they are un stretched. If you need any size image of the diamond let me know and I will make it for you

**Comment by JonathanXu1** [comment]
@sqphoenix Could you provide a screenshot of the favicon issue on Chrome? I'm unable to reproduce it

**Comment by JonathanXu1** [comment]
It seems that older versions of Chrome only support png and .ico. Could I get a 128x128 version of the icon?
