### ISSUE TITLE
[web] Add Chatra

### ISSUE THREAD

**Issue by sqphoenix** [myriadeinc/web#52]
So we want to add in Chatra, which is a chat messaging application for support on our site. In order to integrate it, you need to put in:

[HTML For Chatra.txt](https://github.com/myriadeinc/web/files/4211277/HTML.For.Chatra.txt)

right before the </head> tag. 

Here is their site for documentation. 

https://chatra.io/help/api

**Comment by sqphoenix** [comment]
Sorry for the million edits. I wasn't sure how to copy paste code into the issue

**Comment by JonathanXu1** [comment]
No worries, I'll work on it right after I sort out the docker setup
