### ISSUE TITLE
[web] Hompeage Design Changes

### ISSUE THREAD

**Issue by sqphoenix** [myriadeinc/web#78]
![Pic 1](https://user-images.githubusercontent.com/26234646/80607439-7fb00b00-8a03-11ea-8d66-7c1afaa09aac.png)

1. Switch button Colour to Blue, increase size to make it pop
2. Increase size , push a tad to the left, increase “get Started” button size, and I am sorry to say I was wrong and that the way we had the buttons before “Get Started” & “Login” was better, if less aesthetically pleasing. So put the login button back in. 
3. Change the wording to “Our Mining Pool is in Beta so there will be some issues. Thanks for your Patience!”
4. Increase the size of the logo to match the new increased Dashboard button colour. 
5. This doesn't have a label but change the spinny background to: 0x1122

**Comment by JonathanXu1** [comment]
Just letting you know with respect to 1 and 4, that will make the nav bar much thicker, which might not be good for aesthetics. Are you sure you want that?

**Comment by sqphoenix** [comment]
i was thinking the thickness & opacity of the border of the buttons would be the same as they are now except they'd be white instead of blue
