### ISSUE TITLE
[web] Dashboard cosmetic upgrades

### ISSUE THREAD

**Issue by sqphoenix** [myriadeinc/web#79]
![Pic 2](https://user-images.githubusercontent.com/26234646/80607874-049b2480-8a04-11ea-810a-a0cede31cf0b.png)

1. This is actually good, Ignore the label 
2. Change the name from “Drawings” to “Giveaways” (legal reasons) 
3. As a description write “Enter your Mining Credits for a chance at winning some Monero!”
4. Write “New Game Coming Soon!”

![Group 3](https://user-images.githubusercontent.com/26234646/80607985-2d231e80-8a04-11ea-91b9-258ba4c089d5.png)

1. Change the description to: “Enter your Mining Credits for a chance to win an XMR Prize!”
2. Change the title to: “Monero Giveaways!”
3. Change from “Your Tickets” to “History”

**Comment by JonathanXu1** [comment]
Sounds good :+1:
